name: dropzone_angular_dart
description: DropzoneJS for Angular Dart
version: 0.2.0
author: Nick Ng <ngyewch@gmail.com>
homepage: https://github.com/ngyewch/dropzone-angular-dart

environment:
  sdk: any

dependencies:
  angular: any